spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: develop
  datasource:
    url: jdbc:postgresql://${DB_ADDRESS:localhost}:${DB_PORT:5432}/${DB_NAME:individualTask}
    username: server
    password: server
    driver-class-name: org.postgresql.Driver
  server:
    port: 8080
